---
- name: tao vlan
  hosts: Hihi-Switch
  gather_facts: no

  tasks:
    - name: Create vlan
      ios_vlan:
        vlan_id: "{{ item.number }}"
        name: "{{ item.name }}"
        state: present
      with_items:
        - { number: 50, name: "Account Room" }
        - { number: 51, name: "Authen Room" }
        - { number: 52, name: "Author Room" }

    - name: Show vlan
      ios_command:
        commands:
          - show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
